name: dpt-library
on: [push]
jobs:
  build-library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17']
        # distribution: ['adopt-hotspot', 'adopt-openj9', 'corretto', 'microsoft']
        distribution: ['adopt', 'corretto', 'microsoft']
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Run gradlew clean build
        working-directory: ./library
        run: ./gradlew clean build
