name: dpt-toolkit
on: [push]
jobs:
  build-spark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17']
        distribution: ['adopt', 'corretto', 'microsoft']
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal
      - name: Run gradlew clean build
        working-directory: ./spark
        run: ./gradlew build
