name: Deployment-Library
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: End to end test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dpt-image:test
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Publish to Maven Central
        working-directory: ./library
        uses: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
