name: DataPrivacyToolkit
on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  library:
    name: Library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        distribution: ['temurin', 'corretto', 'microsoft']
    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Run gradlew build
        working-directory: ./library
        run: ./gradlew build --no-daemon

  spark:
    name: Spark
    needs: library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        distribution: ['temurin']
    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal --no-daemon
      - name: Run gradlew build
        working-directory: ./spark
        run: ./gradlew build --no-daemon

  rest:
    name: REST
    needs: library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        distribution: ['temurin', 'corretto', 'microsoft']
    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal --no-daemon
      - name: Run gradlew build
        working-directory: ./rest
        run: ./gradlew build --no-daemon

  docker:
    name: Docker
    needs: library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        distribution: ['temurin', 'corretto', 'microsoft']
    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal --no-daemon
      - name: Run gradlew build
        working-directory: ./docker
        run: ./gradlew build --no-daemon

  end-to-end:
    name: End to end test
    needs: docker
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dpt-image:test
    steps:
      - uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal --no-daemon
      - name: Run gradlew to build toolkit
        working-directory: ./docker
        run: ./gradlew shadowJar -x test --no-daemon
      - name: Build docker image
        working-directory: ./docker
        run: docker build -t $IMAGE_NAME .
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      - name: Install pytest
        working-directory: ./docker
        run: pip install -r ./requirements-dev.txt
      - name: Run end-to-end tests
        working-directory: ./docker
        run: pytest scripts/e2e_tests
