name: end-to-end-toolkit
on: [push]
env:
  IMAGE_NAME: data-privacy-toolkit:${{github.ref}}
jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal
      - name: Run gradlew clean build
        working-directory: ./docker
        run: ./gradlew build
      - name: Build docker image
        working-directory: ./docker
        run: docker build -t $IMAGE_NAME .
      - name: Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - name: Install pytest
        run: pip install pytest==7.2.0
      - name: Run end-to-end test
        working-directory: ./docker
        run: pytest scripts/e2e_tests
