name: DataPrivacyToolkit-REST
on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        distribution: ['temurin', 'corretto', 'microsoft']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Run gradlew publish to maven local
        working-directory: ./library
        run: ./gradlew publishToMavenLocal --no-daemon
      - name: Run gradlew build
        working-directory: ./rest
        run: ./gradlew build --no-daemon
